### ISSUE TITLE
install problem with node-gyp

### ISSUE THREAD

**Issue by stephan-fischer** [codebytere/node-mac-permissions#21]
Hello,

ive got always this error - i tried so many times, reinstalling node-gyp and so on:

```
make: *** [Release/nothing.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Darwin 20.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/...../node_modules/node-mac-permissions
gyp ERR! node -v v14.15.4
gyp ERR! node-gyp -v v7.1.2
gyp ERR! not ok 
npm WARN codelyzer@5.1.2 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-mac-permissions@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-mac-permissions@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Have somebody a hint, tipp or solution for it?
Thank you very much!

Best regards,
Stephan

**Comment by mmaietta** [comment]
> npm WARN codelyzer@5.1.2 requires a peer of tslint@^5.0.0 but none is installed. You must install peer dependencies yourself.

Try adding this to your package.json
```
  "peerDependencies": {
    "tslint": "^5.0.0"
  }
```

**Comment by codebytere** [comment]
Closing in agreement with above.
