### ISSUE TITLE
Gyp issue since last MacOS update

### ISSUE THREAD

**Issue by vddgil** [codebytere/node-mac-permissions#39]
Hello,

Since the update to MacOS 12.3, I have this error when running yarn install.
Any idea?

error /Users/gva/Projects/scribe/desktop-app/node_modules/node-mac-permissions: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/gva/Projects/scribe/desktop-app/node_modules/node-mac-permissions
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.18.2 | darwin | arm64
gyp info find Python using Python version 3.9.10 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
gyp info spawn args [
gyp info spawn args   '/Users/gva/.nodenv/versions/14.18.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/gva/Projects/scribe/desktop-app/node_modules/node-mac-permissions/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/gva/.nodenv/versions/14.18.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/gva/Library/Caches/node-gyp/14.18.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/gva/Library/Caches/node-gyp/14.18.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/gva/.nodenv/versions/14.18.2/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/gva/Library/Caches/node-gyp/14.18.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/gva/Projects/scribe/desktop-app/node_modules/node-mac-permissions',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
env: python: No such file or directory
make: *** [Release/nothing.a] Error 127
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/gva/.nodenv/versions/14.18.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 21.4.0
gyp ERR! command "/Users/gva/.nodenv/versions/14.18.2/bin/node" "/Users/gva/.nodenv/versions/14.18.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gva/Projects/scribe/desktop-app/node_modules/node-mac-permissions

**Comment by KishanBagaria** [comment]
> env: python: No such file or directory

You'll need to install python. macOS 12.3 doesn't include it out of the box anymore.

**Comment by codebytere** [comment]
Yep! I can add it to the README.
