### ISSUE TITLE
Unable to build on M1 mac

### ISSUE THREAD

**Issue by has-n** [codebytere/node-mac-permissions#47]
Pulled our repo onto a M1 MacOS VM and ran `npm install`. When launching the project, I get this error:

> Error: dlopen(/Users/m1/Desktop/Development/app_name/node_modules/node-mac-permissions/build/Release/permissions.node, 0x0001): tried: '/Users/m1/Desktop/Development/app_name/node_modules/node-mac-permissions/build/Release/permissions.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/permissions.node' (no such file), '/usr/lib/permissions.node' (no such file)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at bindings (/Users/m1/Desktop/Development/app_name/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/m1/Desktop/Development/app_name/node_modules/node-mac-permissions/index.js:1:40)

Tried `npm rebuild node-mac-permissions` but doesn't change anything.

The `permissions.target.mk` file has this section
># Flags passed to all source files.
CFLAGS_Debug := \
	-O0 \
	-gdwarf-2 \
	-mmacosx-version-min=10.13 \
	-arch x86_64 \
	-Wall \
	-Wendif-labels \
	-W \
	-Wno-unused-parameter

**Comment by has-n** [comment]
My bad. I was use Node v14.17.3. Upgrading to Node v16.16.0 solved it.
